AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
			AvailabilityZone: 'ap-southeast-1a'
			ImageId: ami-a4c7edb2
			InstanceType: t2.micro
			SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance

  # EC2 Security Group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  # Server Security Group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        - CidrIp: 192.168.1.1/32
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
